config/routes.rb
IdeesBebe::Application.routes.draw do

  root 'welcome#index'
  get '/forbidden' => 'welcome#forbidden', as: 'forbidden'
  
  devise_for :user

  resources :profiles, except: [:index, :create, :new] do
    resources :products, shallow: true
  end

  resources :products, only: [] do
    resources :comments, only: [:create, :destroy], shallow: true
    resources :product_assets, only: [:destroy, :update, :create], shallow: true
    resources :messages, only: [:create, :index, :show]
  end

  resources :categories, only: [:show] do
    get '/:id', action: :show_subcategory, as: 'subcategory'
  end

  post '/profiles/:profile_id/products' => 'products#create', as: 'products'

  resources :inbox, only: [:show, :create]

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  slug             :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  main_category_id :integer
#

class Category < ActiveRecord::Base
  has_many :products
  has_many :subcategories, class_name: 'Category',
                          foreign_key: 'main_category_id'
 
  belongs_to :main_category, class_name: 'Category'

  include Slugable

  before_save :to_slug, if: :name_changed?

  def all_products
    return products unless subcategories.any?
    Product
      .select('categories.name as category_name, categories.slug as category_slug, products.*')
      .where(category_id: subcategories.pluck(:id))
      .joins(:category)
      .order('created_at DESC')
  end

  class << self

    def main_categories
      Category.where(main_category_id: nil)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource :category, find_by: :slug, id_param: :id, only: :show
  load_and_authorize_resource :category, find_by: :slug, id_param: :category_id, only: :show_subcategory

  def show
    @products = @category.all_products
  end

  def show_subcategory
    @subcategory = @category.subcategories.find_by_slug(params[:id])
    @products = @category.all_products
  end
end

app/views/categories/_subcategories.html.haml
#subategories
  - main_category.subcategories.each do |category|
    = link_to category.name, category_subcategory_path(@category.slug, category.slug)
  

app/views/categories/show.html.haml
= render partial: 'categories/subcategories', locals: { main_category: @category }

%h1 Listing products

%table
  %tr
    %th 
    %th Name
    %th Description
    %th
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      - if product.starred_asset
        %td= image_tag(product.starred_asset.thumb.url, alt: product.name, title: product.name)
      - else
        %td= image_tag('default_avatar_thumb.png')
      %td= product.name.capitalize
      %td= product.description
      %td= link_to product.category_name, category_subcategory_path(@category.slug, product.category_slug)
      %td= link_to 'Show', product_path(product.slug)
      - if can? :edit, product
        %td= link_to 'Edit', edit_product_path(product.slug)
      - if can? :destroy, product
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/categories/show_subcategory.html.haml
= render partial: 'categories/subcategories', locals: { main_category: @category }

%h1 Listing products

%table
  %tr
    %th 
    %th Name
    %th Description
    %th
    %th
    %th
  - @products.each do |product|
    %tr
      - if product.starred_asset
        %td= image_tag(product.starred_asset.thumb.url, alt: product.name, title: product.name)
      - else
        %td= image_tag('default_avatar_thumb.png')
      %td= product.name.capitalize
      %td= product.description
      %td= link_to 'Show', product_path(product.slug)
      - if can? :edit, product
        %td= link_to 'Edit', edit_product_path(product.slug)
      - if can? :destroy, product
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

%br