config/routes.rb
IdeesBebe::Application.routes.draw do

  root 'welcome#index'
  get '/forbidden' => 'welcome#forbidden', as: 'forbidden'
  
  devise_for :user

  resources :profiles, except: [:index, :create, :new] do
    resources :products, shallow: true
  end

  resources :products, only: [] do
    resources :comments, only: [:create, :destroy], shallow: true
    resources :product_assets, only: [:destroy, :update, :create], shallow: true
    resources :messages, only: [:create, :index, :show]
  end

  resources :categories, only: [:show] do
    get '/:id', action: :show_subcategory, as: 'subcategory'
  end

  post '/profiles/:profile_id/products' => 'products#create', as: 'products'

  resources :inbox, only: [:show, :create]

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  slug        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  category_id :integer
#

class Product < ActiveRecord::Base

  include Slugable

  MAXIMUM_UPLOAD_PHOTO = 2

  belongs_to :owner, foreign_key: 'user_id', class_name: 'User'
  belongs_to :category

  has_many :assets, foreign_key: 'product_id', class_name: 'ProductAsset', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages

  accepts_nested_attributes_for :category

  validates :name,
    length: {
      minimum: 2,
      maximum: 60,
      message: I18n.t('product.name.length')
    },
    uniqueness: {
      case_sensitive: false,
      message: I18n.t('product.name.uniqueness')
    },
    format: {
      with: /\A[[:digit:][:alpha:]\s'\-_]*\z/u,
      message: I18n.t('product.name.format')
    }

  validates :description,
    length: {
      maximum: 140,
      message: I18n.t('product.description.length')
    },
    allow_blank: true

  validates :category_id, presence: { message: I18n.t('product.category.presence') }

  before_save :to_slug, if: :name_changed?

  def starred_asset
    assets.where(starred: true).first.try(:file)
  end

  def has_maximum_upload?
    assets.count == MAXIMUM_UPLOAD_PHOTO
  end

  def pending_messages_count_for_owner
    last_messages.keep_if{ |msg| msg.sender_id != owner.id }.count
  end

  def last_messages
    ids = potential_buyers_ids
    last_messages = []

    return last_messages if ids.empty? 

    ids.each do |id|
      last_messages << messages.where('receiver_id = ? OR sender_id = ?', id, id).order('created_at DESC').first
    end
    last_messages
  end

  def last_message_with user
    messages.with(user).order('created_at DESC').try(:first)
  end

  private

    def potential_buyers_ids
      messages.where('receiver_id = ?', owner.id).group(:sender_id).order(:sender_id).pluck(:sender_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_resource :user, find_by: :slug, id_param: :profile_id, only: [:index, :new]
  load_and_authorize_resource :product, find_by: :slug, shallow: true, except: [:index, :by_category, :update, :create, :destroy]

  load_and_authorize_resource :product, find_by: :id, shallow: true, only: [:update, :destroy]

  def index
  end
  
  # GET /products/1
  def show
    @comment = Comment.new
    if user_signed_in? and not current_user.is_owner_of? @product
      @message = @product.last_message_with(current_user)
    end
  end

  # GET /profiles/:profile_id/products/new
  def new
    raise CanCan::AccessDenied.new('Not authorized!') if @user != current_user
  end

  # GET /products/1/edit
  def edit
  end

  # POST /profiles/:profile_id/products
  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to product_path(@product.slug), notice: I18n.t('product.create.success')
    else
      render action: :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to edit_product_path(@product.slug), notice: I18n.t('product.update.success')
    else
      render action: :edit
    end
  end

  # DELETE /products/1
  def destroy
    if @product.destroy
      flash[:notice] = I18n.t('product.destroy.success')
    else
      flash[:alert] = I18n.t('product.destroy.error')
    end
    redirect_to products_path(@product.owner.slug)
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :category_id)
    end
end

app/views/products/_comments.html.haml
- unless @product.comments.blank?
  - @product.comments.includes(user: :profile).each do |comment|
    %div
      - if comment.user.avatar?
        = image_tag(comment.user.avatar.thumb.url, alt: comment.user.username, title: comment.user.username)
      - else
        = image_tag('default_avatar_thumb.png')
    %div
      = comment.user.username
      %br
      = comment.content
    - if can? :destroy, comment
      %div
        = link_to 'Supprimer', comment_path(comment.id), method: :delete
%br

app/views/products/_form.html.haml
= simple_form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name, label: 'Nom', input_html: { size: 20 }
  .field
    = f.input :description, label: 'Description'
  .field
    - if @product.category_id.nil?
      = f.association :category, collection: Category.order('main_category_id'), label: 'Catégorie', prompt: "Choisissez une catégorie", hint: "Prenez soin de choisir la bonne catégorie"
    - else
      = f.association :category, collection: Category.order('main_category_id'), label: 'Catégorie', default: @product.category_id, hint: "Prenez soin de choisir la bonne catégorie"
  .actions
    = f.button :submit, 'Sauvegarder'

app/views/products/_form_comments.html.haml
%h3 Commentaires

= form_for @comment, url: product_comments_path(@product.slug) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label 'Content'
    = f.text_field :content
  .actions
    = f.submit 'Sauvegarder'

app/views/products/_form_message_buyer.html.haml
- if not @message
  Contacter le vendeur :
  = simple_form_for Message.new, url: product_messages_path(product_id: @product.id) do |f|
    = f.input :content, label: 'Texte', as: :text
    = f.hidden_field :receiver_id, value: @product.owner.id
    = f.button :submit, 'Contacter'
- else
  - if @message.from_owner?
    Dernier message recu :
    = @message.content
    = simple_form_for Message.new, url: product_messages_path(product_id: @product.id) do |f|
      = f.input :content, label: 'Texte', as: :text
      = f.hidden_field :receiver_id, value: @product.owner.id
      = f.button :submit, 'Contacter'
  - else
    Le vendeur n'a pas encore repondu a votre message

  = link_to 'Voir la conversation', product_message_path(product_id: @product.slug, id: current_user.slug)

app/views/products/_form_message_seller.html.haml
- msg_count = @product.pending_messages_count_for_owner
- if msg_count.zero?
  Vous n'avez aucun nouveaux messages
- else
  = "Vous avez #{msg_count} message(s) en attente(s)"
= link_to 'Gerer mes messages', product_messages_path(product_id: @product.slug)

app/views/products/edit.html.haml
%h1= 'Editer ' + @product.name 

= render 'form'


- unless @product.has_maximum_upload?
  = simple_form_for ProductAsset.new, url: product_product_assets_path(product_id: @product.id), html: { multipart: true }, method: :post  do |f|
    .field
      = f.hidden_field :starred, value: false
      = f.input :file, label: 'Photos', as: :file, allow_blank: true
    .actions
      = f.button :submit, 'Ajouter'
- else
  Vous avez atteint le maximum de photo. Supprimez-en une pour en ajouter de nouvelles

#asset_link
  - @product.assets.each do |a|
    %div
      = image_tag(a.file, alt: @product.description, title: @product.description)
      %div
        - if a.starred
          = image_tag('product_star_thumb.jpg', id: 'img_star', alt: 'Image principale', title: 'Image principale')
        - else
          .star_asset_link
            = simple_form_for a, url: product_asset_path(id: a.id), html: { multipart: true }, method: :put do |f|
              = f.hidden_field :starred, value: true
              = f.button :submit, 'Mettre en avant'
        .destroy_asset_link
          = link_to 'Supprimer', product_asset_path(id: a.id), method: :delete

= link_to 'Retour', product_path(@product.slug)
= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th 
    %th Name
    %th Description
    %th
    %th
    %th
    %th
    %th

  - @user.products.each do |product|
    %tr
      - if product.starred_asset
        %td= image_tag(product.starred_asset.thumb.url, alt: product.name, title: product.name)
      - else
        %td= image_tag('default_avatar_thumb.png')
      %td= product.name.capitalize
      %td= product.description
      %td= "#{product.pending_messages_count_for_owner} messages en attentes"
      %td= link_to 'Gérer mon produit', product_messages_path(product.slug)
      %td= link_to 'Show', product_path(product.slug)
      - if can? :edit, product
        %td= link_to 'Edit', edit_product_path(product.slug)
      - if can? :destroy, product
        %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/products/new.html.haml
%h1 Nouveau produit

= render 'form'

app/views/products/show.html.haml
%p
  %b Nom:
  = @product.name
%p
  %b Description:
  = @product.description

- unless @product.assets.empty?
  #destroy_asset_link
    - @product.assets.each do |a|
      %div
        = image_tag(a.file)
- else
  = image_tag("default_avatar.png")


- if can? :edit, @product
  = link_to 'Editer', edit_product_path(@product.slug)

- if can? :create, @comment
  = render 'products/form_comments'

- if can? :create, Message.new
  = render current_user.is_owner_of?(@product) ? 'products/form_message_seller' : 'products/form_message_buyer'


= render 'products/comments'