config/routes.rb
IdeesBebe::Application.routes.draw do

  root 'welcome#index'
  get '/forbidden' => 'welcome#forbidden', as: 'forbidden'
  
  devise_for :user

  resources :profiles, except: [:index, :create, :new] do
    resources :products, shallow: true
  end

  resources :products, only: [] do
    resources :comments, only: [:create, :destroy], shallow: true
    resources :product_assets, only: [:destroy, :update, :create], shallow: true
    resources :messages, only: [:create, :index, :show]
  end

  resources :categories, only: [:show] do
    get '/:id', action: :show_subcategory, as: 'subcategory'
  end

  post '/profiles/:profile_id/products' => 'products#create', as: 'products'

  resources :inbox, only: [:show, :create]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title IdeesBebe
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    - if current_user
      %div
        = link_to 'Mon profil', profile_path(current_user.slug)
        = link_to 'Mes produits', products_path(current_user.slug)
        = link_to 'Ajouter un produit', new_profile_product_path(profile_id: current_user.slug)
        = link_to 'Deconnexion', destroy_user_session_path, method: :delete
    - else
      %div
        = link_to "S'inscrire", new_user_registration_path
        = link_to 'Se connecter', new_user_session_path

    - Category::main_categories.each do |main|
      %a{ href: category_path(main.slug) }
        = main.name
    = yield